name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pylint
      - name: Run linter
        run: |
          source venv/bin/activate
          pylint src/*.py

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pytest
      - name: Run tests
        run: |
          source venv/bin/activate
          pytest tests

